const EVENT_HANDLER_CREATION_ERROR = "EVENT_HANDLER_CREATION_ERROR";
const REQUEST_HANDLER_CREATION_ERROR = "REQUEST_HANDLER_CREATION_ERROR";
const REQUEST_HANDLER_REGISTRATION_ERROR = "REQUEST_HANDLER_REGISTRATION_ERROR";

export { EVENT_HANDLER_CREATION_ERROR, REQUEST_HANDLER_CREATION_ERROR, REQUEST_HANDLER_REGISTRATION_ERROR }